setool:
  dao:
    executor:
      jdbcTemplateName: jdbcTemplate
  snowflake:
    node:
      type : property
    nodenum: 0
  monitor :
    druid :
      usersql : true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging.level.com.cjunn.setool.monitor.druid.ExecuteSqlMonitorFilter : DEBUG